import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SevenEdu Web App",
  description: "Generated by Telegram Web App",
  other: {
    "google-site-verification": "H3EhWw4ZvxP9sT-kWr_v90NT5DrdlAKL384SlMSMT4U",
  },
  openGraph: {
    title: "SevenEdu – Onlayn Ta'lim Platformasi",
    description:
      "O'zingizga mos kurslar, AI ustozlar va natijalarga asoslangan statistika bilan ta'lim olishingiz mumkin.",
    url: "https://sevenedu.vercel.app/",
    siteName: "SevenEdu",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
