import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SevenEdu Web App",
  description: "Generated by Telegram Web App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
